#ifndef SPELLBOOK_H
#define SPELLBOOK_H

// Spellbook - namespace-wrapped spells generated from save.json
// This file is regenerated by runner/src/spellbook.ts
// DO NOT EDIT MANUALLY - changes will be overwritten
// Template version for generation

#endif  // SPELLBOOK_H
